### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ghost** [Minefly/minefly#1]
### Feature Request

**Checklist:**
- [x] I have read and agree to the [README](https://github.com/Minefly/minefly#readme)
- [ xx] This is not a bug report, support request or plugin request
- [x] I have made sure this issue is not a duplicate

**Platform:**

web
**Describe the feature:**

 sub-users
 People to view code (not edit)
 people to edit/write code
 etc
**Utility:**

Teams

**Use 👍 and 👎 reactions to indicate whether or not agree with this suggestion! Feel free to discuss it in the comments.**
(note: I'm the first #1 very pog)

**Comment by fednelpat** [comment]
Thanks for suggesting! This feature is already in the works
